### ISSUE TITLE
Failed to add

### ISSUE THREAD

**Issue by dclstn** [ucarno/ow-league-tokens#7]
```
Adding an account...
What is your username? (for example myUsername or myUsername#1234) - leave blank to exit
 >>> Vasp#21705
Traceback (most recent call last):
  File "/home/vasp/apps/ow-league-tokens/main.py", line 368, in <module>
    parsed_args.func(parsed_args)
  File "/home/vasp/apps/ow-league-tokens/main.py", line 164, in menu
    users: list = json.loads(response_text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I suspect the API changed in the release of overwatch 2.

**Comment by BadChocMilk** [comment]
Yep, same thing happens to me. My command line also crashes as soon as I input my username. When I tried to do it through command line, the [website to grab player IDs was down](https://overwatch.blizzard.com/en-us/search/account-by-name/username/), either an API change or the script runs off this website and once its back up, it'll work again.

**Comment by ucarno** [comment]
Player profiles are under maintenance. Will leave this issue open in case they change something in the API

**Comment by H0peL3Ss** [comment]
Same problem with me

**Comment by nipser** [comment]
As a workaround, you can get the ID from the overwatchleague.com website:

1. Visit [https://overwatchleague.com/en-us](https://overwatchleague.com/en-us)
2. Login to your account
- That will create a cookie called "account-id" which has the ID you need. How you access this data depends on which brower you use:
3. To get the account-id from the cookie, in
- Firefox: Open developer tools (CTRL + Shift + i), Storage tab, Cookies -> overwatchleague.com -> account-id
- Chromium-browsers: Open developer tools (CTRL + Shift + i), Application tab -> Storage -> Cookies -> overwatchleague.com -> account-id
- Different browser: Use google to find out how to access cookie-data
4. Start the bot using the ID as described here: [https://github.com/ucarno/ow-league-tokens#arguments](https://github.com/ucarno/ow-league-tokens#arguments)
5. You are done so now you have time to call your mom because you probably haven't spoken to her in ages!
